dist: trusty
language: node_js
node_js:
  - "6.9.1"
compiler: clang-3.6
env:
  global:
    - LLVM_VERSION=3.7.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz

before_install:
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang+llvm
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
  - export PATH=$HOME/clang+llvm/bin:$PATH
  # Install the latest npm node-pre-gyp and node-pre-gyp-github
  - npm install -g npm
  - npm install -g node-gyp node-pre-gyp node-pre-gyp-github
  # print versions
  - npm --version
  - node-gyp --version
  - node-pre-gyp --version
  - node-pre-gyp-github --help
